# Generated by Django 5.0.1 on 2026-02-10 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokalizacja', models.CharField(default='lodz', max_length=100)),
                ('cena_min', models.IntegerField(default=100000)),
                ('cena_max', models.IntegerField(default=250000)),
                ('metraz_min', models.IntegerField(blank=True, null=True)),
                ('metraz_max', models.IntegerField(blank=True, null=True)),
                ('balkon', models.BooleanField(default=True)),
                ('garaz', models.BooleanField(default=True)),
                ('piwnica', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Config',
                'verbose_name_plural': 'User Configs',
                'db_table': 'gratka_userconfig',
            },
        ),
        migrations.CreateModel(
            name='UserOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('full_link', models.TextField()),
                ('title', models.TextField()),
                ('price', models.CharField(blank=True, max_length=100)),
                ('area', models.CharField(blank=True, max_length=50)),
                ('rooms', models.CharField(blank=True, max_length=50)),
                ('floor', models.CharField(blank=True, max_length=50)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_scraped', models.DateTimeField(auto_now_add=True)),
                ('sent_to_client', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Offer',
                'verbose_name_plural': 'User Offers',
                'db_table': 'gratka_useroffer',
                'ordering': ['-date_added'],
                'unique_together': {('user', 'offer_id')},
            },
        ),
    ]
