# Generated by Django 5.0.1 on 2026-02-13 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gratka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useroffer',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
